Implement Wireframe Design and Model Methods
MarcoDDM/blog-app pull request #6
Opened 2023-08-31 22:33 UTC by MarcoDDM

**Description:**
This pull request focuses on implementing the wireframe design and enhancing model methods for the Blog App. The goal is to ensure proper functionality and navigation based on the wireframes provided. Additionally, model methods have been enhanced to process data effectively.

**Changes Made:**
- Implemented wireframe design for various pages: All Users, Single User, All Posts by a given User, and Single Post.
- Updated styling to match the design, with a primary focus on functionality.
- Created model methods to handle data processing:
  - Improved the `recent_posts` method to retrieve the most recent posts.
  - Added methods to calculate the counts of posts, comments, and likes for each user.
  - Utilized subqueries to calculate the number of comments and likes associated with posts.
- Reviewed and optimized database queries to ensure efficient data retrieval.
- Added sample data to the database to facilitate testing and visualization of posts and comments.

**Screenshots**
 Added screenshots for the code reviewer convenience.
- Users:
![views_users](https://github.com/MarcoDDM/blog-app/assets/43345162/c9e7be1f-f6da-40cf-9b9b-872079b4fa9b)
- User:
![views_users2](https://github.com/MarcoDDM/blog-app/assets/43345162/a40f6f3e-86d2-4d96-b753-8887279f28b3)
- Posts:
![views_posts](https://github.com/MarcoDDM/blog-app/assets/43345162/3fe6b294-c779-4a9c-9988-c7053a732e33)
- Post:
![views_post](https://github.com/MarcoDDM/blog-app/assets/43345162/e4c48838-ba91-4aeb-a2bc-742655121fa5)

2023-08-31 22:36 UTC, franclobo reviewed
Hi @MarcoDDM, 

# Invalid Code Review Request

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors ❌ 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-31 23:29 UTC, franclobo requested changes
Hi @MarcoDDM, 

# Required Changes ♻️

![so-close-jim-halpert](https://github.com/MarcoDDM/blog-app/assets/58642949/572494bb-5446-4911-b749-5be95c4b3cce)

Good job so far!
You are doing it well 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Git flow ✔️ 
- Use preprocessed HTML file with embedded Ruby code. ✔️ 
- Use layouts and templates for shared content. ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 23:29 UTC, franclobo commented on app/controllers/user_posts_controller.rb
- [ ] According to MVC model the correct name of your controller must be `posts_controller.rb` instead of `user_posts_controller.rb`, please 🙏🏽 correct the name of your controller and update the routes to be similar to the wireframe 👇🏽 

![image](https://github.com/MarcoDDM/blog-app/assets/58642949/59beb182-8318-4b06-b54b-c56d28939dfc)

2023-08-31 23:29 UTC, franclobo commented on app/views/users/index.html.erb
- [ ] The home page of the app is the Rails logo, please 🙏🏽 change your root route to start in the `users#index` page for a better UX.

2023-08-31 23:29 UTC, franclobo commented on app/views/users/index.html.erb
> +            <div class="user-data border">
- [ ] I have charged different images for each user, but it is not possible to see them. Please 🙏🏽 use the correct label and `img` and attribute `src` to load the images for a better UI.

![image](https://github.com/MarcoDDM/blog-app/assets/58642949/b8cbe1cb-4346-4164-8ced-b7e1c3924637)

2023-08-31 23:29 UTC, franclobo commented on app/views/users/show.html.erb
> +      <% end %>
- [ ] According to the wireframe the users#show page should show the users' photo, name, bio, and postCounter, please 🙏🏽 add this to show the most recent posts. After that kindly add a "See all posts" button, to allow the users to see all posts. 

![image](https://github.com/MarcoDDM/blog-app/assets/58642949/2c39c8e7-4b09-4794-ba41-b74d91b49583)

2023-08-31 23:29 UTC, franclobo commented on app/views/users/index.html.erb
> +        <%= link_to user_user_posts_path(user) do %>
- [ ] Ths link should return the users#show page, but it is returning the posts#index page. Please 🙏🏽 correct the path to open the correct page.

2023-08-31 23:29 UTC, franclobo commented on app/views/user_posts/index.html.erb
> +</main>
- [ ] Please 🙏🏽 add the pagination button at the ed of this page to be similar to the wireframe 👇🏽 

| Your design | wireframe |
|---|---|
| ![image](https://github.com/MarcoDDM/blog-app/assets/58642949/b37333b4-1b1f-4da8-9deb-53a7d8ea0331) | ![image](https://github.com/MarcoDDM/blog-app/assets/58642949/77a1ed4c-29e7-429f-98f7-5ca3ae34201c) |

2023-09-01 00:59 UTC, Reem-lab approved these changes
# Hi @MarcoDDM,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights

- [ ]  Followed Gitflow 💯
- [ ]  Descriptive PR⭐
- [ ]  Kudos for working on the requested changes🤩
- [ ]  No Linters error ✅
- [ ] Great job working on the views 🔥



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 01:07 UTC, merged

2023-11-08 00:32 UTC, Davidosky007 reviewed
Hi @MarcoDDM 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has been approved and Merged

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._